import { TARGET_YARN_VERSION } from './context.ts';
import { writeStubYarnRelease } from './stub-yarn.ts';
import type { Workspace } from './workspace.ts';

export interface NpmProjectOptions {
	dependencies?: Record<string, string>;
	devDependencies?: Record<string, string>;
	gitignore?: string | null;
	lockfileVersion?: number;
	name?: string;
	npmrc?: string | null;
	// Declare the manager outright, which also keeps detection from becoming ambiguous.
	packageManager?: string;
	// Pre-vendor the stub release so no download is attempted.
	stubYarnRelease?: boolean;
}

export function packageJsonText(
	name: string,
	dependencies: Record<string, string>,
	options: { devDependencies?: Record<string, string>; indent?: string; packageManager?: string } = {}
): string {
	const manifest: Record<string, unknown> = { name, version: '1.0.0' };
	if (options.packageManager !== undefined) manifest.packageManager = options.packageManager;
	manifest.dependencies = dependencies;
	if (options.devDependencies !== undefined) manifest.devDependencies = options.devDependencies;
	return `${JSON.stringify(manifest, null, options.indent ?? '  ')}\n`;
}

// A project that npm owns: `package-lock.json`, `node_modules` and optionally `.npmrc`.
export async function writeNpmProject(
	workspace: Workspace,
	options: NpmProjectOptions = {}
): Promise<{ name: string }> {
	const name = options.name ?? 'npm-fixture';
	const dependencies = options.dependencies ?? { 'left-pad': '^1.3.0' };
	const manifest: { devDependencies?: Record<string, string>; packageManager?: string } = {};
	if (options.devDependencies !== undefined) manifest.devDependencies = options.devDependencies;
	if (options.packageManager !== undefined) manifest.packageManager = options.packageManager;
	await workspace.write('package.json', packageJsonText(name, dependencies, manifest));
	await workspace.write(
		'package-lock.json',
		`${JSON.stringify(
			{
				lockfileVersion: options.lockfileVersion ?? 3,
				name,
				packages: { '': { dependencies, name, version: '1.0.0' } },
				requires: true,
				version: '1.0.0',
			},
			null,
			2
		)}\n`
	);
	await workspace.write('node_modules/left-pad/index.js', 'module.exports = () => {};\n');
	if (options.gitignore !== null && options.gitignore !== undefined)
		await workspace.write('.gitignore', options.gitignore);
	if (options.npmrc !== null && options.npmrc !== undefined) await workspace.write('.npmrc', options.npmrc);
	if (options.stubYarnRelease === true) await writeStubYarnRelease(workspace);
	return { name };
}

export interface Yarn1ProjectOptions {
	dependencies?: Record<string, string>;
	gitignore?: string | null;
	name?: string;
	yarnrc?: string;
	// Pre-vendor a fake `yarn-1.22.12.cjs` so `prune-releases` has something to delete.
	vendorYarn1Release?: boolean;
}

export const YARN1_RC = [
	'# Yarn 1 settings',
	'registry "https://registry.example.test"',
	'--network-timeout 60000',
	'--ignore-scripts true',
	'yarn-path ".yarn/releases/yarn-1.22.12.cjs"',
	'nohoist **',
	'',
].join('\n');

export function yarn1LockText(dependency = 'left-pad', version = '^1.3.0'): string {
	return `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n${dependency}@${version}:\n  version "1.3.0"\n  resolved "https://registry.yarnpkg.com/${dependency}/-/${dependency}-1.3.0.tgz#abc"\n  integrity sha512-abc\n`;
}

// A project pinned to Yarn 1.22.12 through `.yarnrc` + a `packageManager` field.
export async function writeYarn1Project(
	workspace: Workspace,
	options: Yarn1ProjectOptions = {}
): Promise<{ name: string }> {
	const name = options.name ?? 'yarn1-fixture';
	await workspace.write(
		'package.json',
		packageJsonText(name, options.dependencies ?? { 'left-pad': '^1.3.0' }, {
			packageManager: 'yarn@1.22.12',
		})
	);
	await workspace.write('yarn.lock', yarn1LockText());
	await workspace.write('.yarnrc', options.yarnrc ?? YARN1_RC);
	await workspace.write('node_modules/left-pad/index.js', 'module.exports = () => {};\n');
	if (options.gitignore !== null && options.gitignore !== undefined)
		await workspace.write('.gitignore', options.gitignore);
	if (options.vendorYarn1Release === true) {
		await workspace.write('.yarn/releases/yarn-1.22.12.cjs', '// Yarn 1 release\n');
	}
	return { name };
}

// A project that belongs to pnpm; Drillbit must refuse to convert it.
export async function writePnpmProject(workspace: Workspace): Promise<{ name: string }> {
	const name = 'pnpm-fixture';
	await workspace.write('package.json', packageJsonText(name, { 'left-pad': '^1.3.0' }));
	await workspace.write('pnpm-lock.yaml', "lockfileVersion: '9.0'\n\nimporters:\n  .: {}\n");
	return { name };
}

export { TARGET_YARN_VERSION };
