import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { yarnReleaseRelativePath } from '../../src/core/yarn.ts';
import { TARGET_YARN_VERSION } from './context.ts';
import type { Workspace } from './workspace.ts';

export interface StubInvocation {
	args: string[];
	cwd: string;
	version: string;
}

const STUB_LOG = '.drillbit-stub.jsonl';
// Where the stub records a deliberately simulated failure, so tests never write to inherited stderr
const STUB_ERROR = '.drillbit-stub-error.txt';

export { STUB_ERROR, STUB_LOG };

// A stand-in for `yarn.js` that never touches the network. Drillbit vendors it, then runs it with
// `node .yarn/releases/yarn-<version>.cjs install`, so the migration is exercised end to end while
// staying offline and deterministic. It records every call in `.drillbit-stub.jsonl` and, on a
// successful install, writes the `node_modules` and lockfile a real install would produce.
const STUB_SOURCE = `#!/usr/bin/env node
'use strict';
const { appendFileSync, mkdirSync, readFileSync, writeFileSync } = require('node:fs');
const { join } = require('node:path');

const version = /\\.yarn[\\\\/]releases[\\\\/]yarn-([^\\\\/]+)\\.cjs$/.exec(__filename)?.[1] ?? '0.0.0';
const args = process.argv.slice(2);
const cwd = process.cwd();

appendFileSync(join(cwd, '${STUB_LOG}'), JSON.stringify({ args, cwd, version }) + '\\n');

if (args.length === 0 || args[0] === '--version' || args[0] === '-v') {
	process.stdout.write(version + '\\n');
	process.exit(0);
}

if (process.env.DRILLBIT_STUB_FAIL === '1') {
	writeFileSync(join(cwd, '${STUB_ERROR}'), 'STUB_FAIL: refusing to install\\n');
	process.exit(1);
}

if (args[0] !== 'install') {
	process.stderr.write('STUB_UNSUPPORTED: ' + args[0] + '\\n');
	process.exit(1);
}

const manifest = JSON.parse(readFileSync(join(cwd, 'package.json'), 'utf8'));
const names = Object.keys({ ...manifest.dependencies, ...manifest.devDependencies });
for (const name of names) {
	const directory = join(cwd, 'node_modules', name);
	mkdirSync(directory, { recursive: true });
	writeFileSync(
		join(directory, 'package.json'),
		JSON.stringify({ name, version: '1.0.0', main: 'index.js' }, null, 2) + '\\n'
	);
	writeFileSync(join(directory, 'index.js'), 'module.exports = {};\\n');
}

const lockfile = [
	'# This file is generated by the Drillbit test stub. DO NOT EDIT.',
	'__metadata:',
	'  version: 10',
	'  cacheKey: 10',
	'',
	...names.flatMap((name) => [
		'"' + name + '@npm:1.0.0":',
		'  version: 1.0.0',
		'  resolution: "' + name + '@npm:1.0.0"',
		'',
	]),
].join('\\n');
writeFileSync(join(cwd, 'yarn.lock'), lockfile);
`;

async function readStubLog(workspace: Workspace): Promise<StubInvocation[]> {
	const raw = await readFile(join(workspace.dir, STUB_LOG), 'utf8').catch(() => '');
	return raw
		.split('\n')
		.filter((line) => line.trim() !== '')
		.map((line) => JSON.parse(line) as StubInvocation);
}

// Pre-vendors the stub so `vendor-yarn` finds a release already in place and skips the download
// Returns the path Drillbit will run
export async function writeStubYarnRelease(
	workspace: Workspace,
	version = TARGET_YARN_VERSION
): Promise<{ log: () => Promise<StubInvocation[]>; relative: string }> {
	await workspace.write(yarnReleaseRelativePath(version), STUB_SOURCE);
	return { log: () => readStubLog(workspace), relative: yarnReleaseRelativePath(version) };
}

export { readStubLog };
